[package]
name = "store"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.172"
rtrb = "0.3.2" # temporary, to simulate network connections

[dev-dependencies]
ciborium = "0.2.2"
rand = "0.9.0"
rand_chacha = "0.9.0"
serde = "1.0.219"
