cargo-features = ["edition2024"]

[package]
name = "store"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
libc = "0.2.172"

[dev-dependencies]
rand = "0.9.0"
rand_chacha = "0.9.0"
