page_size = 16384
buf_pool_size = 1024
free_cap_target = 128

block_size = 32000
num_block_bufs = 4
# 1tb total file capacity (this is a hack for now and will be removed when gc is implemented
block_cap = 1073741824

net_buf_size = 2048
num_net_bufs = 1024

queue_size = 1024
